from manim import *

class GeoSeq(Scene):
    def construct(self):
        

        eq = MathTex(r"f(x)", color = PINK)
        eq_sign = MathTex("=", color = PINK)
        eq1 = MathTex(r"\frac{1}{2} + \frac{1}{4} + \frac{1}{8} + \frac{1}{16} + \frac{1}{32} + \cdots + \frac{1}{2^n} + \cdots", color = PINK)
        eq_sign1 = MathTex("=", color = PINK)
        eq2 = MathTex(r"\sum_{n=1}^{\infty} \frac{1}{2^{n}}", color = PINK)
        eq_sign2 = MathTex(r"=", color = PINK)
        eq_sign.shift(UP, UP, LEFT, LEFT, LEFT, LEFT)
        eq.next_to(eq_sign, LEFT)
        eq1.next_to(eq_sign, RIGHT)
        self.play(Write(eq))
        self.wait(0.5)
        self.play(Write(eq_sign))
        self.play(Write(eq1), run_time = 4)
        self.wait(0.5)
        eq_sign1.shift(LEFT,LEFT, LEFT, LEFT)
        eq2.next_to(eq_sign1, RIGHT)
        self.play(Write(eq_sign1))
        self.play(Write(eq2), run_time = 3)
        self.play(FadeOut(eq, eq_sign1, eq1, eq_sign))
        self.play(eq2.animate.shift(LEFT, UP, LEFT, UP))
        self.wait(0.5)
        s = Square(3, fill_opacity = 1.0, fill_color = DARK_GRAY)
        self.play(DrawBorderThenFill(s))
        one = MathTex(r"1", color = PINK)
        one1 = MathTex(r"1",color = PINK)
        one.next_to(s, LEFT)
        one1.next_to(s, UP)
        self.play(Write(one))
        self.play(Write(one1))
        A = MathTex(r"Area", color = PINK)
        A.next_to(s, RIGHT)
        self.play(Write(A), run_time = 1)
        eq_sign2.next_to(A, RIGHT)
        self.play(Write(eq_sign2), run_time = 0.5)
        var = VGroup(one, one1)
        eq3 = MathTex(r"{{a}}^2", color = PINK)
        eq3.next_to(eq_sign2, RIGHT)
        eq4 = MathTex(r"{{1}}^2", color = PINK)
        eq4.next_to(eq_sign2, RIGHT)
        self.play(Write(eq3), run_time = 1)
        self.wait(0.5)
        self.play(TransformMatchingTex(Group(eq3, var), eq4))
        eq5 = MathTex(r"{{1}}", color = PINK)
        var1 = VGroup(eq4)
        self.play(FadeOut(eq_sign2))
        self.play(TransformMatchingTex(Group(A, var1), eq5))
        self.wait(1)
        self.play(FadeOut(eq5), run_time = 0.75)
        self.wait(0.5)
        
        r1 = Rectangle(width = 3/2, height = 3, fill_opacity = 1.0, fill_color = TEAL)
        r1.shift(0.75 * LEFT)
        self.play(DrawBorderThenFill(r1))
        oh = MathTex(r"\frac{1}{2}", color = PINK)
        
        r2 = Rectangle(width = 3/2, height = 3/2, fill_opacity = 1.0, fill_color = BLUE)
        oq = MathTex(r"\frac{1}{4}", color = PINK)
        r2.shift(0.75 * RIGHT, 0.75 * DOWN)
        self.play(DrawBorderThenFill(r2))

        r3 = Rectangle(width = 3/4, height = 3/2, fill_opacity = 1.0, fill_color = GREEN)
        oe = MathTex(r"\frac{1}{8}", color = PINK)
        r3.shift(9/8 * RIGHT, 0.75 * UP)
        self.play(DrawBorderThenFill(r3))
        
        r4 = Rectangle(width = 3/4, height = 3/4, fill_opacity = 1.0, fill_color = YELLOW)
        os = MathTex(r"\frac{1}{16}", color = PINK)
        r4.shift(3/8 * RIGHT,  9/8 * UP)
        self.play(DrawBorderThenFill(r4))
        
        r5 = Rectangle(width = 3/8, height = 3/4, fill_opacity = 1.0, fill_color = ORANGE)
        ot = MathTex(r"\frac{1}{32}", color = PINK)
        r5.shift(3/16 * RIGHT, 3/8 * UP)
        self.play(DrawBorderThenFill(r5))

        r6 = Rectangle(width = 3/8, height = 3/8, fill_opacity = 1.0, fill_color = RED)
        os1 = MathTex(r"\frac{1}{64}", color = PINK)
        r6.shift(9/16 * RIGHT, 3/16 * UP)
        self.play(DrawBorderThenFill(r6))

        r7 = Rectangle(width = 3/16, height = 3/8, fill_opacity = 1.0, fill_color = MAROON)
        oo = MathTex(r"\frac{1}{128}", color = PINK)
        r7.shift((9/16 + 9/96) * RIGHT, 9/16 * UP)
        self.play(DrawBorderThenFill(r7))

        r8 = Rectangle(width = 3/16, height = 3/16, fill_opacity = 1.0, fill_color = PURPLE)
        ot1 = MathTex(r"\frac{1}{256}", color = PINK)
        r8.shift((45/96) * RIGHT, (9/16 + 9/96) * UP)
        self.play(DrawBorderThenFill(r8))

        r9 = Rectangle(width = 3/16, height = 3/16, fill_opacity = 1.0, fill_color = PINK)
        of = MathTex(r"\frac{1}{2^{n+8}}", color = PINK)
        r9.shift((45/96) * RIGHT, (3/8 + 3/32) * UP)
        self.play(DrawBorderThenFill(r9)) 

        self.play(FadeOut(s))

        recs = VGroup(r1, r2, r3, r4, r5, r6 ,r7 ,r8, r9)
        self.play(recs.animate.shift(DOWN))

        
        eq_sign.next_to(eq2, RIGHT)
        alh = MathTex(r"{{\frac{1}{2} + \frac{1}{4} + \frac{1}{8} + \frac{1}{16} + \frac{1}{32} + \frac{1}{64} + \frac{1}{128} + \frac{1}{254} + \frac{1}{2^{n+8}}}}", color = PINK)
        
        self.play(Write(eq_sign))
        oh.next_to(eq_sign, RIGHT)
        self.play(Write(oh))
        self.play(r1.animate.scale(0).move_to(oh))

        ad = MathTex(r"+", color = PINK)
        ad1 = MathTex(r"+", color = PINK)
        ad2 = MathTex(r"+", color = PINK)
        ad3 = MathTex(r"+", color = PINK)
        ad4 = MathTex(r"+", color = PINK)
        ad5 = MathTex(r"+", color = PINK)
        ad6 = MathTex(r"+", color = PINK)
        ad7 = MathTex(r"+", color = PINK)
        ad8 = MathTex(r"+", color = PINK)

        ad.next_to(oh, 1/2 * RIGHT)
        self.play(Write(ad))
        oq.next_to(ad, 1/2 * RIGHT)
        self.play(Write(oq))
        self.play(r2.animate.scale(0).move_to(oq))
        ad1.next_to(oq, RIGHT)
        self.play(Write(ad1))
        oe.next_to(ad1,1/2 * RIGHT)
        self.play(Write(oe))
        self.play(r3.animate.scale(0).move_to(oe))
        ad2.next_to(oe,1/2 *  RIGHT)
        self.play(Write(ad2))
        os.next_to(ad2,1/2 *  RIGHT)
        self.play(Write(os))
        self.play(r4.animate.scale(0).move_to(os))
        ad3.next_to(os,1/2 *  RIGHT)
        self.play(Write(ad3))
        ot.next_to(ad3,1/2 *  RIGHT)
        self.play(Write(ot))
        self.play(r5.animate.scale(0).move_to(ot))
        ad4.next_to(ot,1/2 *  RIGHT)
        self.play(Write(ad4))
        os1.next_to(ad4,1/2 *  RIGHT)
        self.play(Write(os1))
        self.play(r6.animate.scale(0).move_to(os1))
        ad5.next_to(os1,1/2 *  RIGHT)
        self.play(Write(ad5))
        oo.next_to(ad5,1/2 *  RIGHT)
        self.play(Write(oo))
        self.play(r7.animate.scale(0).move_to(oo))
        ad6.next_to(oo,1/2 *  RIGHT)
        self.play(Write(ad6))
        ot1.next_to(ad6,1/2 *  RIGHT)
        self.play(Write(ot1))
        self.play(r8.animate.scale(0).move_to(ot1))
        ad7.next_to(ot1,1/2 *  RIGHT)
        self.play(Write(ad7))
        of.next_to(ad7,1/2 *  RIGHT)
        self.play(Write(of))
        self.play(r9.animate.scale(0).move_to(of))
        
        
        hs = VGroup(ad, ad1, ad2, ad3, ad4, ad5, ad6, ad7, oh, oq, oe ,os , ot, os1, oo, ot1, of)
        eq5.next_to(eq_sign, RIGHT)

        fsign = MathTex(r"=", color = PINK)
        self.play(Write(fsign))
        eq5.next_to(fsign, RIGHT)
        self.play(Write(eq5))
        self.play(FadeOut(hs, eq_sign))
        self.play(eq2.animate.next_to(fsign, LEFT))

        self.wait(2)
        self.play(FadeOut(eq2, eq5, fsign), run_time=1)
